### PR TITLE
Grabbing Matt's changes in from his branch1

### PR DESCRIPTION
**Pull request by trje9656**

### CODE REVIEW

**Comment by Spaceman1701** [comment]
#1 already covers these changes, I think

**Comment by Spaceman1701** [comment]
You don't need to create PRs for your own dev branches. PRs should only be used for merging into master or other people's branches.

**Comment by trje9656** [comment]
I'm just gonna clone his repo and grab the changed files instead cause this conflict is a pain.

**Comment by Spaceman1701** [comment]
You're probably going to need to manually resolve the conflicts.

**Comment by trje9656** [comment]
As long as I don't grab the conflicted files I should be fine, the original conflict was in tabledef.pyc, which isn't a important file to keep I'm pretty sure.

**Pull request closed without merging**
